### PR TITLE
SLING-9030 less verbose logging for retryable-distribution-failures …

### PR DESCRIPTION
**Pull request by actinium15**
…in SimpleDistributionAgentQueueProcessor

### CODE REVIEW

**Review by cschneider — CHANGES_REQUESTED** [review]
Thanks for the PR. I think it indeed makes sense to not log on error level.
I think it is not a good practice though to check for the debug level and then decide between logging on ERROR or WARN level. I suggest to simply lower the logging to WARN in general here.

**Comment by tmaret** [comment]
@actinium15 I share @cschneider view here. Simply logging at WARN level makes sense.

**Comment by cschneider** [comment]
Why did you close the PR ? I requested to change the PR to reflect logging at WARN level.

**Comment by actinium15** [comment]
>I suggest to simply lower the logging to WARN in general here.

@cschneider, I didn't want to lose the full exception and stack trace, and (for obvious reasons) didn't want to include that in the WARN log.

>I think it is not a good practice though to check for the debug level and then decide between logging on ERROR or WARN level

Would you prefer if I just log the exception additionally if debug is enabled? (as in `if (log.isDebugEnabled()) log.error(e);`), or are you suggesting `log.debug(e)`? (latter has the chances of being missed if one were to run grep on large logs in production)

Or are you of the opinion that logging the full exception and trace is of not value at any log level?

\cc: @tmaret

**Comment by cschneider** [comment]
I think logging the exception only if debug is enabled is good. It is just that I would not change the general log level. So I propose to log on WARN level and in case of debug level add the exception to the log message.

**Pull request closed without merging**
