### PR TITLE
SLING-7359: prevent distribution loop in triggers from distribution events

### PR DESCRIPTION
**Pull request by buuhuu**
This is done by exposing information of the trigger.DispatcherRequestHandler to the trigger implementations, which allow them to filter events they are handling. The DistributionEventDistributeDistributionTrigger has been changed to not propagate events to the handler which have there origin at the handler's owner itself.

### CODE REVIEW

**Comment by tteofili** [comment]
@Buuhuu could you please rebase against latest trunk, merging of PR #2 requires now _TestSerializer_ in _FileDistributionPackageBuilderTest_ implements #getContentType.

**Comment by tteofili** [comment]
sorry, it was my mistake not having rebased PR #2 when merging it. I'll fix it and then we can apply this PR.

**Comment by buuhuu** [comment]
I updated the PR already

**Comment by tteofili** [comment]
thanks @Buuhuu

**Pull request merged**
