### PR TITLE
SLING-11579 Error Distribution queue is not getting created on  forwa…

### PR DESCRIPTION
**Pull request by malpani0311**
…rd agent creation

### CODE REVIEW

**Comment by malpani0311** [comment]
Error Distribution queue is not getting created on  forward agent creation due to mismatch of config variables.
https://github.com/apache/sling-org-apache-sling-distribution-core/blob/master/src/main/java/org/apache/sling/distribution/agent/impl/ForwardDistributionAgentFactory.java#L94
RETRY_STRATEGY should be "retry.strategy"

RETRY_ATTEMPTS  should be "retry.attempts"

**Review by tmaret — COMMENTED** [review]
How does this affect error queues ?

This change would break existing configuration which adopted the current naming.

**Comment by malpani0311** [comment]
> How does this affect error queues ?
> This is preventing creation of error queue. "retryStrategy" is coming as null on line[0] which prevents creation of this queue from line[1].

[0]: https://github.com/apache/sling-org-apache-sling-distribution-core/blob/master/src/main/java/org/apache/sling/distribution/agent/impl/ForwardDistributionAgentFactory.java#L241
[1]: https://github.com/apache/sling-org-apache-sling-distribution-core/blob/master/src/main/java/org/apache/sling/distribution/agent/impl/ForwardDistributionAgentFactory.java#L245
> This change would break existing configuration which adopted the current naming.
AFAIU isn't it will adapt new naming convention , once we install it again. Please correct me if i am wrong here.

@tmaret

**Comment by malpani0311** [comment]
@tmaret  @mohiaror  please review

**Comment by mohiaror** [comment]
@tmaret  The agents that were created using this factory with the bug would not get the errorQueue which is a bug. AFAIU, no existing configurations (faulty or not) would not be affected by this change.

**Comment by tmaret** [comment]
@mohiaror I think we are aligned, all existing deployment which configured error queue with the current naming convention, would be affected by this change. We can fix this, but it needs to come with a warning in the release summary or a major version bump.

**Comment by malpani0311** [comment]
> @tmaret The agents that were created using this factory with the bug would not get the errorQueue which is a bug. AFAIU, no existing configurations (faulty or not) would not be affected by this change.

@mohiaror I think error queue will be created once this fix deployed and bundle installation completed.
I have tried on local setup which have distribution agent created by this factory and error queue was not present.
After installation error queue is created .

**Comment by malpani0311** [comment]
@tmaret :
Here are currently my findings :
We are recreating agents on activation through our implementation code[0] which means error queue will also be created after installation.
If there is processing queue which have items which also will retrieved once installation completed.
In that case they won't get the fix.

So what are next steps we can take it from here to get this PR merge as its been pressing issue for brand portal.
[0]: https://git.corp.adobe.com/CQ/mac-damsync/blob/master/bundles/brandportal/src/main/java/com/adobe/cq/dam/bp/cloudconfig/impl/MediaPortalCloudConfigurationListener.java#L229 

CC: @mohiaror

**Comment by malpani0311** [comment]
@tmaret 
We can divide customers on 3 types based on naming convictions change[0] .

Before commit[0],

Customer already have errors queue and this customers will not be impacted by this change.

After Commit[0],

Error queues started not getting automatically after agent creation due to mismatch of variable names.

After this change ,

 Agents will be created on activation through our implementation code[1] which means error queue will also be created after installation.

>I think we are aligned, all existing deployment which configured error queue with the current naming convention, would be affected by this change. 


I want to understand how they will be impacted **by this change** because currently they don't have error queue created at all.



> The agents that were created using this factory with the bug would not get the errorQueue which is a bug. AFAIU, no existing configurations (faulty or not) would not be affected by this change.

Agreed.

[0]: https://github.com/apache/sling-org-apache-sling-distribution-core/blame/master/src/main/java/org/apache/sling/distribution/agent/impl/ForwardDistributionAgentFactory.java#L94
[1]: https://git.corp.adobe.com/CQ/mac-damsync/blob/master/bundles/brandportal/src/main/java/com/adobe/cq/dam/bp/cloudconfig/impl/MediaPortalCloudConfigurationListener.java#L229

**Comment by malpani0311** [comment]
@tmaret Can you please review above comments

**Comment by tmaret** [comment]
@malpani0311 I did review and also looked at the code history. You are fixing a regression that was introduced in the big refactoring tracked in SLING-8595. Thank you, and sorry for the confusion.

**Review by tmaret — APPROVED** [review]

**Pull request merged**
